development:
  adapter: mysql2
  encoding: utf8
  database: amkhmer_development
  pool: 5
  username: root
  password:
test:
  adapter: mysql2
  encoding: utf8
  database: amkhmer_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: amkhmer_production
  pool: 5
  username: amkhmer
  password:
